name: Deploy Docs to GitHub Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Put dummy env vars
        run: |
          cd ./.cargo
          cat <<EOF > config.toml
          [env]
          MAPS_API_KEY = ${{ env.MAPS_API_KEY }}
          EOF
          echo "cat config.toml"
          cat config.toml

      - name: Build Docs
        run: |
          cargo doc --no-deps

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./target/doc"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
